openapi: 3.0.0
info:
  title: WISEducation API
  description: API contract for WISEducation platform covering Auth, Market, Education, Community, and Simulation.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local Development Server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        avatarUrl:
          type: string
        reputationPoints:
          type: integer

    Portfolio:
      type: object
      properties:
        totalBalance:
          type: number
        growthPercentage:
          type: number
        history:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
              value:
                type: number

    Stock:
      type: object
      properties:
        ticker:
          type: string
        name:
          type: string
        price:
          type: number
        changePercent:
          type: number
        changeValue:
          type: number
        volume:
          type: string
        marketCap:
          type: string
        peRatio:
          type: string
        sector:
          type: string
        description:
          type: string
        logoUrl:
          type: string

    Course:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        difficulty:
          type: string
          enum: [Beginner, Intermediate, Advanced]
        coverImageUrl:
          type: string
        progress:
          type: integer
          description: Percentage completed (0-100)
        totalDurationMinutes:
          type: integer

    Post:
      type: object
      properties:
        id:
          type: string
        author:
          $ref: '#/components/schemas/User'
        content:
          type: string
        createdAt:
          type: string
          format: date-time
        type:
          type: string
          enum: [text, image, poll]
        upvotes:
          type: integer
        commentCount:
          type: integer
        tags:
          type: array
          items:
            type: string
        pollOptions:
          type: array
          items:
            type: object
            properties:
              label:
                type: string
              votes:
                type: integer
        imageUrl:
          type: string

    Activity:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        description:
          type: string
        timestamp:
          type: string
          format: date-time
        metadata:
          type: object

paths:
  # Authentication
  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'

  /auth/me:
    get:
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  # Dashboard / User Data
  /user/portfolio:
    get:
      summary: Get user portfolio summary
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Portfolio data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Portfolio'

  /user/activities:
    get:
      summary: Get recent user activities
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of activities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'

  # Market Data
  /market/stocks:
    get:
      summary: Get list of stocks
      responses:
        '200':
          description: List of stocks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stock'

  /market/stocks/{ticker}:
    get:
      summary: Get stock details
      parameters:
        - in: path
          name: ticker
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Stock details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'

  # Education
  /education/modules:
    get:
      summary: Get learning modules
      parameters:
        - in: query
          name: difficulty
          schema:
            type: string
        - in: query
          name: search
          schema:
            type: string
      responses:
        '200':
          description: List of modules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'

  /education/modules/{id}/progress:
    post:
      summary: Update module progress
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                progress:
                  type: integer
      responses:
        '200':
          description: Progress updated

  # Community
  /community/posts:
    get:
      summary: Get community feed
      parameters:
        - in: query
          name: sort
          schema:
            type: string
            enum: [trending, new, top]
        - in: query
          name: filter
          schema:
            type: string
      responses:
        '200':
          description: Feed posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      summary: Create a new post
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                type:
                  type: string
                  enum: [text, image, poll]
                imageUrl:
                  type: string
      responses:
        '201':
          description: Post created

  /community/contributors:
    get:
      summary: Get top contributors
      responses:
        '200':
          description: List of top contributors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  # AI Assistant
  /ai/chat:
    post:
      summary: Send message to AI mentor
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                context:
                  type: string
      responses:
        '200':
          description: AI response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
